"""Recursive code tracer for a 32 KiB (single bank) Game Boy ROM.

Finds which bytes are code by following control flow from the entry points,
including jump tables: a table of addresses right after an `rst` (game.json
"jump_table_rst") or a call to a dispatcher routine ("jump_table_calls"). Writes an mgbdis .sym file that marks code and data blocks
and names the discovered entry points.

    python tools/trace.py tetris.gb  ->  tetris.sym
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import build  # noqa: E402
from sm83 import decode  # noqa: E402

JUMPTABLE_RST = build.GAME['jump_table_rst']   # `rst $xx` + table of addresses, or None
# routines that are called with a table of addresses right after the call (game.json:
# "jump_table_calls": ["0x0229"]) - they pop it as their return address and jump through it
JUMPTABLE_TARGETS = ({JUMPTABLE_RST} if JUMPTABLE_RST is not None else set()) |     {int(a, 0) for a in build.GAME.get('jump_table_calls', [])}
ENTRY_POINTS = {
    0x0100: 'Boot',
    0x0000: 'RST_00',
    0x0008: 'RST_08',
    0x0028: 'RST_28',
    0x0040: 'VBlankInterrupt',
    0x0048: 'LCDCInterrupt',
    0x0050: 'TimerOverflowInterrupt',
    0x0058: 'SerialTransferCompleteInterrupt',
}
# code nothing refers to, but that is clearly code (game.json: "trace_entries": {"0x0153": "Name"})
ENTRY_POINTS.update({int(a, 0): n for a, n in build.GAME.get('trace_entries', {}).items()})


def trace(rom, table_limits):
    """One tracing pass. table_limits: {table_addr: max_entries or None}."""
    size = len(rom)
    code = {}            # addr -> Insn
    calls = set()        # call/rst targets
    jumps = set()        # jump targets
    tables = {}          # table_addr -> [targets]
    work = list(ENTRY_POINTS)
    seen = set()
    while work:
        pc = work.pop()
        while 0 <= pc < size and pc not in seen:
            insn = decode(rom, pc)
            if insn.kind == 'invalid':
                break
            seen.add(pc)
            code[pc] = insn
            nxt = pc + insn.length
            k = insn.kind
            if k in ('jump', 'cjump'):
                jumps.add(insn.target)
                work.append(insn.target)
            elif k in ('call', 'ccall', 'rst'):
                calls.add(insn.target)
                work.append(insn.target)
                if insn.target in JUMPTABLE_TARGETS:
                    t = nxt
                    limit = table_limits.get(t)
                    entries = []
                    a = t
                    while a + 1 < size and (limit is None or len(entries) < limit):
                        w = rom[a] | (rom[a + 1] << 8)
                        if not (0x0040 <= w < 0x8000) or 0x0104 <= w < 0x0150:
                            break
                        entries.append(w)
                        a += 2
                    tables[t] = entries
                    for w in entries:
                        jumps.add(w)
                        work.append(w)
                    break
            if k in ('jump', 'ret', 'jphl', 'stop'):
                break
            pc = nxt
    return code, calls, jumps, tables


def code_bytes(code):
    s = set()
    for a, i in code.items():
        s.update(range(a, a + i.length))
    return s


def run(rom):
    limits = {}
    for _ in range(50):
        code, calls, jumps, tables = trace(rom, limits)
        cb = code_bytes(code)
        starts = set(code)
        changed = False
        for t, entries in tables.items():
            # a table ends where code (or another table) begins
            n = 0
            for i in range(len(entries)):
                a = t + 2 * i
                if a in cb or a + 1 in cb or a in starts:
                    break
                if i and any(a == t2 for t2 in tables if t2 != t):
                    break
                n += 1
            if limits.get(t) != n:
                limits[t] = n
                changed = True
        if not changed:
            break
    return code, calls, jumps, tables


def main():
    rom_path = sys.argv[1]
    rom = open(rom_path, 'rb').read()
    code, calls, jumps, tables = run(rom)
    cb = code_bytes(code)
    size = len(rom)

    # contiguous code / data ranges
    blocks = []
    a = 0
    while a < size:
        is_code = a in cb
        b = a
        while b < size and (b in cb) == is_code:
            b += 1
        blocks.append((a, b - a, 'code' if is_code else 'data'))
        a = b

    table_bytes = set()
    for t, e in tables.items():
        table_bytes.update(range(t, t + 2 * len(e)))

    labels = dict(ENTRY_POINTS)
    for t in tables:
        labels.setdefault(t, 'JumpTable_{:04X}'.format(t))
    for c in calls:
        labels.setdefault(c, 'Call_{:04X}'.format(c))
    for e in tables.values():
        for w in e:
            labels.setdefault(w, 'Jump_{:04X}'.format(w))

    out = [';; generated by tools/trace.py - code/data map for mgbdis']
    for a, n, kind in blocks:
        out.append('00:{:04x} .{}:{:x}'.format(a, kind, n))
    for a in sorted(labels):
        out.append('00:{:04x} {}'.format(a, labels[a]))
    sym_path = os.path.splitext(rom_path)[0] + '.sym'
    open(sym_path, 'w').write('\n'.join(out) + '\n')

    info = {
        'code_bytes': len(cb),
        'data_bytes': size - len(cb),
        'functions': len(calls),
        'tables': {'{:04X}'.format(t): ['{:04X}'.format(w) for w in e] for t, e in tables.items()},
    }
    print(json.dumps({k: v for k, v in info.items() if k != 'tables'}))
    for t, e in sorted(tables.items()):
        print('table ${:04X}: {} entries'.format(t, len(e)))


if __name__ == '__main__':
    main()
